# Predict bandgap of Polymers

+ Name - Prathamesh Rajesh Sonar
+ project - Built a Machine learning model to predict the band gap of polymers(atoms).
+ Date - 09/03/2024
- A prediction model using machine learning to predict the band gap of polymers...
-here we have use:
1. pandas
2. numpy
3. matplotlib
4. rdkit (use for chemical formulas to get array of equation of polymer)
5. ensemble technique (i have created my own ensemble model for regression purpose with hyperparameter tunned)

In [5]:
'''conda create -n myenv python=3.8 rdkit
conda config
conda install rdkit
pip --version
pip install rdkit-pypi'''

'conda create -n myenv python=3.8 rdkit\nconda config\nconda install rdkit\npip --version\npip install rdkit-pypi'

In [70]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import AllChem
import warnings
warnings.filterwarnings('ignore')

In [71]:
df = pd.read_csv('train.csv')
df1 = pd.read_csv('test.csv')
d= pd.read_csv('sample_submission.csv')

In [72]:
df1 = pd.concat([df1,d['band_gap']],axis=1)

In [73]:
df1.head(3)

,id,polymer,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,...,fp_o_desc_chi1n,fp_o_desc_chi1v,fp_o_desc_chi2n,fp_o_desc_chi2v,fp_o_desc_chi3n,fp_o_desc_chi3v,fp_o_desc_chi4n,fp_o_desc_chi4v,fp_o_desc_HallKierAlpha,band_gap
0,402,[*]CCN[Si](C)(C)N[*],1,0.0,0.0,0.000000,0.0,0.0,0.0,0.5,...,0.673409,1.425826,0.612559,1.59683,0.295143,0.830742,0.191847,0.575542,0.034221,2
1,321,[*]C=Cc1ccc(C=Cc2nc3cc4nc([*])[nH]c4cc3[nH]2)cc1,1,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.398572,0.398572,0.301130,0.30113,0.216130,0.216130,0.152212,0.152212,0.174444,2
2,457,[*]CC([*])C(=O)c1ccc(Br)cc1,1,0.0,0.0,0.111111,0.0,0.0,0.0,0.0,...,0.395481,0.483592,0.306438,0.40818,0.221428,0.280169,0.156136,0.185506,0.070000,2

In [74]:
df.head(3)

,id,polymer,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,...,fp_o_desc_chi1n,fp_o_desc_chi1v,fp_o_desc_chi2n,fp_o_desc_chi2v,fp_o_desc_chi3n,fp_o_desc_chi3v,fp_o_desc_chi4n,fp_o_desc_chi4v,fp_o_desc_HallKierAlpha,band_gap
0,789,[*]C(=O)c1ccc2c(c1)C(=O)N(c1ccc(C3(c4ccc(N5C(=...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.377963,0.377963,0.300679,0.300679,0.245471,0.245471,0.192698,0.192698,0.160238,2.3311
1,2983,[*]CCCCCOC(=O)c1ccc(C(=O)NCCCCCCNC(=O)c2ccc(C(...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.074074,...,0.449784,0.449784,0.310747,0.310747,0.209719,0.209719,0.132236,0.132236,0.136296,4.3426
2,1037,[*]CNON[*],1,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,...,1.093414,1.093414,0.536822,0.536822,0.266744,0.266744,0.136920,0.136920,0.120000,5.3302

In [75]:
df.head(2)

,id,polymer,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,...,fp_o_desc_chi1n,fp_o_desc_chi1v,fp_o_desc_chi2n,fp_o_desc_chi2v,fp_o_desc_chi3n,fp_o_desc_chi3v,fp_o_desc_chi4n,fp_o_desc_chi4v,fp_o_desc_HallKierAlpha,band_gap
0,789,[*]C(=O)c1ccc2c(c1)C(=O)N(c1ccc(C3(c4ccc(N5C(=...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.377963,0.377963,0.300679,0.300679,0.245471,0.245471,0.192698,0.192698,0.160238,2.3311
1,2983,[*]CCCCCOC(=O)c1ccc(C(=O)NCCCCCCNC(=O)c2ccc(C(...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.074074,...,0.449784,0.449784,0.310747,0.310747,0.209719,0.209719,0.132236,0.132236,0.136296,4.3426

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2534 entries, 0 to 2533
Data columns (total 87 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2534 non-null   int64
 1   polymer                  2534 non-null   object
 2   fp_mqns_1                2534 non-null   int64
 3   fp_mqns_2                2534 non-null   float64
 4   fp_mqns_3                2534 non-null   float64
 5   fp_mqns_4                2534 non-null   float64
 6   fp_mqns_5                2534 non-null   float64
 7   fp_mqns_6                2534 non-null   float64
 8   fp_mqns_7                2534 non-null   float64
 9   fp_mqns_8                2534 non-null   float64
 10  fp_mqns_9                2534 non-null   float64
 11  fp_mqns_10               2534 non-null   float64
 12  fp_mqns_11               2534 non-null   float64
 13  fp_mqns_12               2534 non-null   float64
 14  fp_mqns_13               2534 non-null   float64
 15  fp_mqns_14               2534 non-null   float64
 16  fp_mqns_15               2534 non-null   float64
 17  fp_mqns_16               2534 non-null   float64
 18  fp_mqns_17               2534 non-null   float64
 19  fp_mqns_18               2534 non-null   int64
 20  fp_mqns_19               2534 non-null   float64
 21  fp_mqns_20               2534 non-null   float64
 22  fp_mqns_21               2534 non-null   float64
 23  fp_mqns_22               2534 non-null   float64
 24  fp_mqns_23               2534 non-null   float64
 25  fp_mqns_24               2534 non-null   float64
 26  fp_mqns_25               2534 non-null   float64
 27  fp_mqns_26               2534 non-null   float64
 28  fp_mqns_27               2534 non-null   float64
 29  fp_mqns_28               2534 non-null   float64
 30  fp_mqns_29               2534 non-null   float64
 31  fp_mqns_30               2534 non-null   float64
 32  fp_mqns_31               2534 non-null   float64
 33  fp_mqns_32               2534 non-null   float64
 34  fp_mqns_33               2534 non-null   float64
 35  fp_mqns_34               2534 non-null   float64
 36  fp_mqns_35               2534 non-null   float64
 37  fp_mqns_36               2534 non-null   float64
 38  fp_mqns_37               2534 non-null   float64
 39  fp_mqns_38               2534 non-null   float64
 40  fp_mqns_39               2534 non-null   int64
 41  fp_mqns_40               2534 non-null   int64
 42  fp_mqns_41               2534 non-null   float64
 43  fp_mqns_42               2534 non-null   float64
 44  fp_smrVsa_1              2534 non-null   float64
 45  fp_smrVsa_2              2534 non-null   float64
 46  fp_smrVsa_3              2534 non-null   float64
 47  fp_smrVsa_4              2534 non-null   float64
 48  fp_smrVsa_5              2534 non-null   float64
 49  fp_smrVsa_6              2534 non-null   float64
 50  fp_smrVsa_7              2534 non-null   float64
 51  fp_smrVsa_8              2534 non-null   int64
 52  fp_smrVsa_9              2534 non-null   float64
 53  fp_smrVsa_10             2534 non-null   float64
 54  fp_slogPVsa_1            2534 non-null   float64
 55  fp_slogPVsa_2            2534 non-null   float64
 56  fp_slogPVsa_3            2534 non-null   float64
 57  fp_slogPVsa_4            2534 non-null   float64
 58  fp_slogPVsa_5            2534 non-null   float64
 59  fp_slogPVsa_6            2534 non-null   float64
 60  fp_slogPVsa_7            2534 non-null   float64
 61  fp_slogPVsa_8            2534 non-null   float64
 62  fp_slogPVsa_9            2534 non-null   int64
 63  fp_slogPVsa_10           2534 non-null   float64
 64  fp_slogPVsa_11           2534 non-null   float64
 65  fp_slogPVsa_12           2534 non-null   float64
 66  fp_o_desc_nRotBon        2534 non-null   float64
 67  fp_o_desc_nRing          2534 non-null   float64
 68  fp_o_desc_nAroRing       2534 non-null   float64
 69  fp_o_desc_nAliRing       2534 non-null   float64
 70  fp_o_desc_k1             2534 non-null   float64
 71  fp_o_desc_k2             2534 non-null   float64
 72  fp_o_desc_k3             2534 non-null   float64
 73  fp_o_desc_chi0           2534 non-null   float64
 74  fp_o_desc_chi0n          2534 non-null   float64
 75  fp_o_desc_chi0v          2534 non-null   float64
 76  fp_o_desc_chi1           2534 non-null   float64
 77  fp_o_desc_chi1n          2534 non-null   float64
 78  fp_o_desc_chi1v          2534 non-null   float64
 79  fp_o_desc_chi2n          2534 non-null   float64
 80  fp_o_desc_chi2v          2534 non-null   float64
 81  fp_o_desc_chi3n          2534 non-null   float64
 82  fp_o_desc_chi3v          2534 non-null   float64
 83  fp_o_desc_chi4n          2534 non-null   float64
 84  fp_o_desc_chi4v          2534 non-null   float64
 85  fp_o_desc_HallKierAlpha  2534 non-null   float64
 86  band_gap                 2534 non-null   float64
dtypes: float64(79), int64(7), object(1)
memory usage: 1.7+ MB

In [77]:
df = df.drop('id',axis=1)

* We drop id column as it is unnecessary

In [78]:
df.isnull().sum()

polymer                    0
fp_mqns_1                  0
fp_mqns_2                  0
fp_mqns_3                  0
fp_mqns_4                  0
                          ..
fp_o_desc_chi3v            0
fp_o_desc_chi4n            0
fp_o_desc_chi4v            0
fp_o_desc_HallKierAlpha    0
band_gap                   0
Length: 86, dtype: int64

* So, there is no null data.
* now we will convert polymer formulas into arrays.

In [79]:
polymer_ = [np.array(AllChem.GetMorganFingerprintAsBitVect(Chem.MolFromSmiles(i), 2)) for i in df.polymer]

In [80]:
df.polymer

0       [*]C(=O)c1ccc2c(c1)C(=O)N(c1ccc(C3(c4ccc(N5C(=...
1       [*]CCCCCOC(=O)c1ccc(C(=O)NCCCCCCNC(=O)c2ccc(C(...
2                                              [*]CNON[*]
3         [*]Oc1ccc(-c2ccc(OC(=O)CCCCCCCCC([*])=O)cc2)cc1
4                                    [*]OC1(O)CCCC([*])C1
                              ...
2529    [*]C(=O)Nc1ccc(-c2ccc(NC(=O)c3ccc4c(c3)C(=O)N(...
2530              [*]CC(C)(C)COC(=O)NCCCC(CCNC(=O)O[*])OC
2531                                  [*]C=CC(C[*])C(C)CC
2532                [*]Cc1nc(-c2ccc(-c3csc([*])n3)cc2)cs1
2533           [*]N=C(N=C(NC(C)=O)NC(C)=O)N=C([*])OC(C)=O
Name: polymer, Length: 2534, dtype: object

In [81]:
df['polymer1'] = polymer_

In [82]:
df.head(3)

,polymer,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,fp_mqns_9,...,fp_o_desc_chi1v,fp_o_desc_chi2n,fp_o_desc_chi2v,fp_o_desc_chi3n,fp_o_desc_chi3v,fp_o_desc_chi4n,fp_o_desc_chi4v,fp_o_desc_HallKierAlpha,band_gap,polymer1
0,[*]C(=O)c1ccc2c(c1)C(=O)N(c1ccc(C3(c4ccc(N5C(=...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.047619,...,0.377963,0.300679,0.300679,0.245471,0.245471,0.192698,0.192698,0.160238,2.3311,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,[*]CCCCCOC(=O)c1ccc(C(=O)NCCCCCCNC(=O)c2ccc(C(...,1,0.0,0.0,0.0,0.0,0.0,0.0,0.074074,0.000000,...,0.449784,0.310747,0.310747,0.209719,0.209719,0.132236,0.132236,0.136296,4.3426,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, ..."
2,[*]CNON[*],1,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,0.000000,...,1.093414,0.536822,0.536822,0.266744,0.266744,0.136920,0.136920,0.120000,5.3302,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [83]:
df = df.drop('polymer',axis=1)

In [84]:
df.head(3)

,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,fp_mqns_9,fp_mqns_10,...,fp_o_desc_chi1v,fp_o_desc_chi2n,fp_o_desc_chi2v,fp_o_desc_chi3n,fp_o_desc_chi3v,fp_o_desc_chi4n,fp_o_desc_chi4v,fp_o_desc_HallKierAlpha,band_gap,polymer1
0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.047619,0.119048,...,0.377963,0.300679,0.300679,0.245471,0.245471,0.192698,0.192698,0.160238,2.3311,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.074074,0.000000,0.222222,...,0.449784,0.310747,0.310747,0.209719,0.209719,0.132236,0.132236,0.136296,4.3426,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, ..."
2,1,0.0,0.0,0.0,0.0,0.0,0.0,2.000000,0.000000,1.000000,...,1.093414,0.536822,0.536822,0.266744,0.266744,0.136920,0.136920,0.120000,5.3302,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [85]:
df.columns

Index(['fp_mqns_1', 'fp_mqns_2', 'fp_mqns_3', 'fp_mqns_4', 'fp_mqns_5',
       'fp_mqns_6', 'fp_mqns_7', 'fp_mqns_8', 'fp_mqns_9', 'fp_mqns_10',
       'fp_mqns_11', 'fp_mqns_12', 'fp_mqns_13', 'fp_mqns_14', 'fp_mqns_15',
       'fp_mqns_16', 'fp_mqns_17', 'fp_mqns_18', 'fp_mqns_19', 'fp_mqns_20',
       'fp_mqns_21', 'fp_mqns_22', 'fp_mqns_23', 'fp_mqns_24', 'fp_mqns_25',
       'fp_mqns_26', 'fp_mqns_27', 'fp_mqns_28', 'fp_mqns_29', 'fp_mqns_30',
       'fp_mqns_31', 'fp_mqns_32', 'fp_mqns_33', 'fp_mqns_34', 'fp_mqns_35',
       'fp_mqns_36', 'fp_mqns_37', 'fp_mqns_38', 'fp_mqns_39', 'fp_mqns_40',
       'fp_mqns_41', 'fp_mqns_42', 'fp_smrVsa_1', 'fp_smrVsa_2', 'fp_smrVsa_3',
       'fp_smrVsa_4', 'fp_smrVsa_5', 'fp_smrVsa_6', 'fp_smrVsa_7',
       'fp_smrVsa_8', 'fp_smrVsa_9', 'fp_smrVsa_10', 'fp_slogPVsa_1',
       'fp_slogPVsa_2', 'fp_slogPVsa_3', 'fp_slogPVsa_4', 'fp_slogPVsa_5',
       'fp_slogPVsa_6', 'fp_slogPVsa_7', 'fp_slogPVsa_8', 'fp_slogPVsa_9',
       'fp_slogPVsa_10', 'fp_slogPVsa_11', 'fp_slogPVsa_12',
       'fp_o_desc_nRotBon', 'fp_o_desc_nRing', 'fp_o_desc_nAroRing',
       'fp_o_desc_nAliRing', 'fp_o_desc_k1', 'fp_o_desc_k2', 'fp_o_desc_k3',
       'fp_o_desc_chi0', 'fp_o_desc_chi0n', 'fp_o_desc_chi0v',
       'fp_o_desc_chi1', 'fp_o_desc_chi1n', 'fp_o_desc_chi1v',
       'fp_o_desc_chi2n', 'fp_o_desc_chi2v', 'fp_o_desc_chi3n',
       'fp_o_desc_chi3v', 'fp_o_desc_chi4n', 'fp_o_desc_chi4v',
       'fp_o_desc_HallKierAlpha', 'band_gap', 'polymer1'],
      dtype='object')

In [86]:
for column in df.columns:
    if df[column].dtype in [int,float]: 
        print(df[column].min(),(df[column].max()))

0.0 2.333333333
0.0 1.5
0.0 1.0
0.0 1.0
0.0 1.0
0.0 0.125
0.0 2.0
0.0 1.0
0.0 2.0
0.0 0.5
1.0 5.0
0.03125 3.958333333
0.0 1.0
0.0 0.666666667
0.0 1.5
0.0 1.0
0.0 3.625
0.0 6.0
0.0 4.0
0.0 2.25
0.0 2.125
0.0 0.333333333
0.0 0.333333333
0.0 2.375
0.0 3.75
0.0 1.0
0.0 0.96875
0.0 1.28125
0.0 0.9921875
0.0 0.859375
0.0 0.2
0.0 0.25
0.0 0.4
0.0 0.333333333
0.0 0.142857143
0.0 0.125
0.0 0.714285714
0.0 0.9
0.0 11.95414142
0.0 3.507927703
0.0 10.27518112
0.0 3.944295023
0.0 6.518227121
0.0 6.83254921
0.0 6.138884554
0.0 4.187833774
0.0 22.59087063
0.0 11.01230306
0.0 11.33622268
0.0 9.070478595
0.0 9.4009817
0.0 7.437280654
0.0 6.138884554
0.0 3.273505677
0.0 4.187833774
0.0 10.24430178
0.0 2.784919794
0.0 22.59087063
0.0 3.625
0.0 0.5
0.0 0.375
0.0 0.5
0.104939496 4.65
0.133676353 3.755
0.039614971 3.63
0.611786109 3.771893917
0.532873864 2.711393869
0.506445856 3.147532609
0.432871614 2.378372945
0.284699493 1.329670031
0.244417725 1.950662278
0.141930999 0.678718935
0.141930999 2.529142536
0.063623286 0.590196749
0.063623286 2.15665441
0.028461104 0.612819616
0.028461104 1.695476892
0.0 0.77
0.069 9.8627

In [87]:
from sklearn.preprocessing import MinMaxScaler

In [88]:
scaler = MinMaxScaler()

In [89]:
numeric_columns = df.select_dtypes(include=['int64','float64']).columns

In [90]:
scaled_data = scaler.fit_transform(df[numeric_columns])

In [91]:
scaled_df = pd.DataFrame(scaled_data, columns=numeric_columns)

In [92]:
scaled_df = pd.concat([scaled_df, df.drop(columns=numeric_columns)], axis=1)

In [93]:
scaled_df.head(5)

,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,fp_mqns_9,fp_mqns_10,...,fp_o_desc_chi1v,fp_o_desc_chi2n,fp_o_desc_chi2v,fp_o_desc_chi3n,fp_o_desc_chi3v,fp_o_desc_chi4n,fp_o_desc_chi4v,fp_o_desc_HallKierAlpha,band_gap,polymer1
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.047619,0.059524,...,0.078269,0.295737,0.066499,0.345341,0.086882,0.281055,0.098521,0.208101,0.230975,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.037037,0.000000,0.111111,...,0.120362,0.314493,0.070717,0.277445,0.069801,0.177588,0.062252,0.177008,0.436362,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, ..."
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.000000,0.500000,...,0.497582,0.735655,0.165419,0.385741,0.097046,0.185603,0.065062,0.155844,0.537202,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.090909,...,0.104832,0.293408,0.065976,0.266105,0.066948,0.185109,0.064888,0.154664,0.459571,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.166667,...,0.167663,0.590210,0.132714,0.505703,0.127227,0.411797,0.144352,0.017316,0.611015,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [94]:
polymer_column = scaled_df['polymer1']
flattened_arrays = pd.DataFrame(polymer_column.tolist(), columns=[f'element_{i}' for i in range(len(polymer_column[0]))])
processed_df = pd.concat([scaled_df.drop(columns=['polymer1']), flattened_arrays], axis=1)
processed_df

,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,fp_mqns_9,fp_mqns_10,...,element_2038,element_2039,element_2040,element_2041,element_2042,element_2043,element_2044,element_2045,element_2046,element_2047
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.047619,0.059524,...,0,0,0,0,0,0,0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.037037,0.000000,0.111111,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.000000,0.000000,0.500000,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.090909,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.166667,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2529,0.0,0.0,0.0,0.0,0.0,0.023810,0.0,0.023810,0.047619,0.095238,...,0,0,0,0,0,0,0,0,0,0
2530,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.071429,0.000000,0.178571,...,0,0,0,0,0,0,0,0,0,0
2531,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
2532,0.0,0.0,0.0,0.0,0.0,0.153846,0.0,0.000000,0.153846,0.000000,...,0,0,0,0,0,0,0,0,0,0
2533,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.277778,0.000000,0.222222,...,0,0,0,0,0,0,0,0,0,0

In [95]:
X = processed_df.drop('band_gap',axis=1)
X

,fp_mqns_1,fp_mqns_2,fp_mqns_3,fp_mqns_4,fp_mqns_5,fp_mqns_6,fp_mqns_7,fp_mqns_8,fp_mqns_9,fp_mqns_10,...,element_2038,element_2039,element_2040,element_2041,element_2042,element_2043,element_2044,element_2045,element_2046,element_2047
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.047619,0.059524,...,0,0,0,0,0,0,0,0,0,0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.037037,0.000000,0.111111,...,0,0,0,0,0,0,0,0,0,0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,1.000000,0.000000,0.500000,...,0,0,0,0,0,0,0,0,0,0
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.090909,...,0,0,0,0,0,0,0,0,0,0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.166667,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2529,0.0,0.0,0.0,0.0,0.0,0.023810,0.0,0.023810,0.047619,0.095238,...,0,0,0,0,0,0,0,0,0,0
2530,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.071429,0.000000,0.178571,...,0,0,0,0,0,0,0,0,0,0
2531,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.000000,...,0,0,0,0,0,0,0,0,0,0
2532,0.0,0.0,0.0,0.0,0.0,0.153846,0.0,0.000000,0.153846,0.000000,...,0,0,0,0,0,0,0,0,0,0
2533,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.277778,0.000000,0.222222,...,0,0,0,0,0,0,0,0,0,0

In [96]:
y = processed_df['band_gap']
y

0       0.230975
1       0.436362
2       0.537202
3       0.459571
4       0.611015
          ...
2529    0.245964
2530    0.623186
2531    0.499842
2532    0.390088
2533    0.374087
Name: band_gap, Length: 2534, dtype: float64

In [35]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV

model_selection = {
    "LinearRegression" : {
        "model" : LinearRegression(),
        "params" : {}
    },
    "Ridge" :{
        "model" : Ridge(),
        "params" : {'alpha':[1,2,3,4,5,6,7,8,9]}
    },
    "Lasso" : {
        "model": Lasso(),
        "params":{'alpha':[1,2,3,4,5,6,7,8,9]}
    },
    "ElasticNet" : {
        "model": ElasticNet(),
        "params":{'alpha':[1,2,3,4,5,6,7,8,9],
                 'l1_ratio':[0.5,1,1.5,2,2.5,3]}
    },
    "DecisionTreeRegressor" : {
        "model": DecisionTreeRegressor(),
        "params":{"criterion": ["squared_error"],
                  'splitter':['random']}
    },
    "RandomForestRegressor" : {
        "model": RandomForestRegressor(),
        "params":{'n_estimators':[20],
                 "criterion": ['absolute_error']}
    },
    "GradientBoostingRegressor" : {
        "model": GradientBoostingRegressor(),
        "params":{'loss':['squared_error', 'absolute_error', 'huber', 'quantile'],
                 'n_estimators':[10],
                  'criterion':['friedman_mse', 'squared_error']
                 }
    }
   
                   }

In [36]:
best_estimators = {}
scores = []

for model_name,model_params in model_selection.items():
    print(f'performing GridSearchCV {model_name}...')
    clf = GridSearchCV(model_params['model'],model_params['params'],cv=5,scoring='neg_mean_squared_error')
    clf.fit(X,y)
    best_estimators[model_name] = clf.best_estimator_
    print(f'Beat Parameters for {model_name} :  {clf.best_params_}')
    print(f"Best MSE for {model_name}: {clf.best_score_}")
    scores.append({
        'model':model_name,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })
final_score = pd.DataFrame(scores,columns=['model','best_score','best_params'])
final_score

performing GridSearchCV LinearRegression...
Beat Parameters for LinearRegression :  {}
Best MSE for LinearRegression: -3.0366792649103245e+17
performing GridSearchCV Ridge...
Beat Parameters for Ridge :  {'alpha': 7}
Best MSE for Ridge: -0.003466178724878595
performing GridSearchCV Lasso...
Beat Parameters for Lasso :  {'alpha': 1}
Best MSE for Lasso: -0.02526163826816278
performing GridSearchCV ElasticNet...
Beat Parameters for ElasticNet :  {'alpha': 1, 'l1_ratio': 0.5}
Best MSE for ElasticNet: -0.02526163826816278
performing GridSearchCV DecisionTreeRegressor...
Beat Parameters for DecisionTreeRegressor :  {'criterion': 'squared_error', 'splitter': 'random'}
Best MSE for DecisionTreeRegressor: -0.005842459972377633
performing GridSearchCV RandomForestRegressor...
Beat Parameters for RandomForestRegressor :  {'criterion': 'absolute_error', 'n_estimators': 20}
Best MSE for RandomForestRegressor: -0.0033923747864479255
performing GridSearchCV GradientBoostingRegressor...
Beat Parameters for GradientBoostingRegressor :  {'criterion': 'friedman_mse', 'loss': 'squared_error', 'n_estimators': 10}
Best MSE for GradientBoostingRegressor: -0.008906943149816372

,model,best_score,best_params
0,LinearRegression,-3.036679e+17,{}
1,Ridge,-3.466179e-03,{'alpha': 7}
2,Lasso,-2.526164e-02,{'alpha': 1}
3,ElasticNet,-2.526164e-02,"{'alpha': 1, 'l1_ratio': 0.5}"
4,DecisionTreeRegressor,-5.842460e-03,"{'criterion': 'squared_error', 'splitter': 'ra..."
5,RandomForestRegressor,-3.392375e-03,"{'criterion': 'absolute_error', 'n_estimators'..."
6,GradientBoostingRegressor,-8.906943e-03,"{'criterion': 'friedman_mse', 'loss': 'squared..."

* Here is built in Ensemble technique to get the best score and parameters...
* So, we can see L2 Regularization or Ridge regression is the best model and the hyperparameter is:

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=5)

In [52]:
model = Ridge(alpha= 7)
model.fit(x_train,y_train)
pre = model.predict(x_test)

In [53]:
from sklearn.metrics import r2_score
score = r2_score(y_test,pre)
score

0.8523968923992187

# Thank you